// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { removeCorruptSupabaseAuthStorage } from '@/utils/supabaseSessionCleanup';

const SUPABASE_URL = "https://kydmyxsgyxeubhmqzrgo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt5ZG15eHNneXhldWJobXF6cmdvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0ODQ3NjQsImV4cCI6MjA2MjA2MDc2NH0.b-ckDfOmmf2x__FG5Snm9px8j4pqPke5Ra1RgoGEqP0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

removeCorruptSupabaseAuthStorage();

const wait = (ms: number) => new Promise((resolve) => setTimeout(resolve, ms));

const shouldRetryRequest = (input: RequestInfo | URL, init?: RequestInit) => {
  const url = String(input);
  const method = (init?.method || (input instanceof Request ? input.method : 'GET')).toUpperCase();

  return method === 'GET' || method === 'HEAD' || url.includes('/rest/v1/rpc/get_home_books_fast');
};

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  global: {
    fetch: async (input, init) => {
      const canRetry = shouldRetryRequest(input, init);

      for (let attempt = 0; attempt < (canRetry ? 3 : 1); attempt += 1) {
        try {
          const response = await fetch(input, init);

          if ((response.status === 401 || response.status === 403) && String(input).includes('/auth/v1/')) {
            removeCorruptSupabaseAuthStorage();
          }

          return response;
        } catch (error) {
          if (!canRetry || attempt === 2) throw error;
          await wait(700 * (attempt + 1));
        }
      }

      return fetch(input, init);
    }
  }
});

export const supabaseFunctions = supabase;